### PR TITLE
Try and fix flakey device list update after leave

### LINKED ISSUE #1036: `If remote user leaves room we no longer receive device updates` is flakey
See https://github.com/matrix-org/synapse/pull/9855/checks?check_run_id=2412069509

### PR DESCRIPTION
**Pull request by erikjohnston**
Hopefully fixes #1036, but I was unable to reproduce it locally, so :shrug: 

The only race I could think of here is that the creator's HS receives the device list update for the left user while its still processing the leave of that user, but that seems fairly unlikely.

### CODE REVIEW

File: tests/41end-to-end-keys/06-device-lists.pl [hunk 1]
```diff
@@ -397,10 +397,28 @@ sub sync_until_user_in_device_list
...
+         # wait for the leave to propagate to the creators homeserver
+         await_sync_timeline_contains( $creator, $room_id, check => sub {
+            my ( $event ) = @_;
+
+            assert_json_keys( $event, qw( type content sender ));
+
+            return unless $event->{type} eq "m.room.member";
+            return unless $event->{sender} eq $remote_leaver->user_id;
+
+
```
Comment (richvdh) [inline tests/41end-to-end-keys/06-device-lists.pl:413]:
```suggestion
```

File: tests/41end-to-end-keys/06-device-lists.pl [hunk 2]
```diff
@@ -397,10 +397,28 @@ sub sync_until_user_in_device_list
...
+            assert_json_keys( my $content = $event->{content}, qw( membership ));
+
+            return unless $content->{membership} eq "leave";
+
+            return 1;
+         });
+      })->then( sub {
+
```
Comment (richvdh) [inline tests/41end-to-end-keys/06-device-lists.pl:421]:
```suggestion
```

**Review by richvdh — APPROVED** [review]
Don't the logs give any clues as to the problem?

Seems ok, anyway.

**Comment by erikjohnston** [comment]
> Don't the logs give any clues as to the problem?

Not that I saw, alas, though I might easily have missed something given the sheer number of workers
