### PR TITLE
Fix flakey test for /messages

### LINKED ISSUE #1026: `A prev_batch token from incremental sync can be used in the v1 messages API` is flakey
see https://buildkite.com/matrix-dot-org/synapse/builds/16739#eef8037b-bff5-46c9-94c5-2a9cc66ce5bb

### PR DESCRIPTION
**Pull request by erikjohnston**
Fixes `A prev_batch token from incremental sync can be used in the v1 messages API...`.

Fixes #1026

### CODE REVIEW

File: tests/31sync/04timeline.pl [hunk 1]
```diff
@@ -403,6 +403,9 @@
          my ( $body ) = @_;
 
          my $room = $body->{rooms}{join}{$room_id};
+
+	 log_if_fail "Sync for room", $room;
```
Comment (richvdh) [inline tests/31sync/04timeline.pl:407]:
```suggestion
         log_if_fail "Sync for room", $room;
```

**Review by richvdh — APPROVED** [review]

File: tests/31sync/04timeline.pl (hunk 1 above)
Comment (erikjohnston) [reply tests/31sync/04timeline.pl:407]: Oh for gods sake vim
