### PR TITLE
Fix bad tests

### LINKED ISSUE #913: Sytest asserts optional fields in /sync
https://github.com/matrix-org/sytest/blob/24bc7c431881042fa5094815b98dff61532480d1/tests/10apidoc/03events-initial.pl#L231

### PR DESCRIPTION
**Pull request by timokoesters**
Fixes #913 and #919

### CODE REVIEW

File: tests/10apidoc/11profile-avatar_url.pl [hunk 1]
```diff
@@ -1,6 +1,6 @@
 my $user_fixture = local_user_fixture();
 
-my $avatar_url = "http://somewhere/my-pic.jpg";
+my $avatar_url = "mxc://example.com/SEsfnsuifSDFSSEF";
```
Comment (anoadragon453) [inline tests/10apidoc/11profile-avatar_url.pl:3]: Heads up this definitely isn't the only occurrence of an `http://` URL being used as an avatar in the codebase.

**Review by erikjohnston — APPROVED** [review]
Thanks!
